# -*- coding: utf-8 -*-
"""lecture13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/notice4/google-colab-study/blob/main/lecture13.ipynb
"""

from transformers import pipeline

model = pipeline('sentiment-analysis')

model('i hate cats and love dogs')

import requests
from bs4 import BeautifulSoup

# The Goodreads quote URL
review_url = 'https://www.goodreads.com/quotes'

# Set a User-Agent header
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

try:
    response = requests.get(review_url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, 'html.parser')

    # Find all quote containers
    for quote_tag in soup.find_all("div", class_="quoteText"):

        # 1. Access the first text content directly.
        # This contents list usually looks like: [Quote Text, <br/>, '\n  ―\n  \n    ', <span>author info</span>]
        # The quote text is the first item in the list.
        if quote_tag.contents:
            quote_text = quote_tag.contents[0].strip()

            # 2. Extract the author's name from the child span for a complete result
            author_span = quote_tag.find("span", class_="authorOrTitle")
            author_name = author_span.text.strip() if author_span else "Unknown Author"

            print(f'Emotion of {quote_text}: {model(quote_text)[0]['label']}')
            #print(f'Author: {author_name}')
            #print("-" * 40)

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

import requests
from bs4 import BeautifulSoup

requestUrl = 'https://www.goodreads.com/quotes'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

try:
    response = requests.get(requestUrl, headers=headers)
    response.raise_for_status()
    soup = BeautifulSoup(response.content, 'html.parser')

    for quote_tag in soup.find_all("div", class_="quoteText"):
      if quote_tag.contents:
        quote_text = quote_tag.contents[0].strip()

        autor_span = quote_tag.find("span", class_="authorOrTitle")
        author_name = autor_span.text.strip() if autor_span else "Unknown Author"

        print(f'Emotion of {quote_text}: {model(quote_text)[0]["label"]}')
        print(f'Author: {author_name}')
        print("-" * 40)

except requests.exceptions.RequestException as e:
  print(f"An error occurred: {e}")

